// Document checklists per application type — based on IRCC requirements (2024-2025)

export const CHECKLISTS: Record<string, string[]> = {
  EXPRESS_ENTRY: [
    "Valid passport — must have at least 6 months validity beyond your expected entry date",
    "Language test results — IELTS General Training or CELPIP-General (all 4 bands, min CLB 7) OR TEF Canada / TCF Canada",
    "Educational Credential Assessment (ECA) — from WES or another IRCC-designated organization",
    "Proof of work experience — employment reference letters on company letterhead (NOC code, job duties, dates, salary, hours/week signed by HR/supervisor)",
    "Pay stubs or T4 slips for Canadian work experience (if applicable)",
    "Proof of settlement funds — official bank statements from last 6 months (waived if you have a valid Canadian job offer)",
    "Police certificates — from every country you lived in for 6+ months since age 18",
    "Upfront medical exam — from a designated IRCC panel physician (results valid 12 months)",
    "Two photos — must meet IRCC photo specifications (35mm × 45mm, plain white background)",
    "Spouse/partner documents (if applicable): passport, language test, ECA, police certificate, marriage/common-law proof",
    "Provincial Nomination Certificate (if applying under PNP stream — adds 600 CRS points)",
    "Completed IMM 0008 — General Application Form for Canada",
  ],
  PNP: [
    "Provincial Nomination Certificate — issued by the nominating province/territory",
    "Valid passport (min 6 months validity after expected entry)",
    "Language test results — IELTS, CELPIP, TEF Canada, or TCF Canada (min CLB 7 for most streams)",
    "Educational Credential Assessment (ECA) if degrees obtained outside Canada",
    "Proof of work experience — reference letters on company letterhead with NOC code",
    "Job offer letter from Canadian employer (if applicable to your stream)",
    "Proof of settlement funds — official bank statements",
    "Police certificates from all countries of residence 6+ months since age 18",
    "Medical exam from IRCC-designated panel physician",
    "Proof of settlement plans in the nominating province",
    "Two passport-style photos",
  ],
  STUDY_PERMIT: [
    "Letter of Acceptance from a Designated Learning Institution (DLI) — confirm your school is on the DLI list",
    "Provincial Attestation Letter (PAL) — required since January 22, 2024 (contact your school's admissions office)",
    "Valid passport — must cover entire duration of your study program plus 90 days",
    "Proof of financial support — tuition fees + at least $10,000/year for living expenses",
    "Bank statements (last 4-6 months) showing sufficient funds OR scholarship/government loan letter",
    "Statement of Purpose — explaining why you chose this program, school, and plan to return home",
    "Academic transcripts, diplomas, and certificates from previous institutions",
    "Language test (IELTS/TOEFL/DELF/DALF) if program is in English or French",
    "Proof of ties to home country — employment letter, property ownership, family obligations",
    "Biometrics — if this is your first application or biometrics have expired",
    "Two passport-style photos",
  ],
  WORK_PERMIT: [
    "Job offer letter on employer letterhead — must include: position title, NOC code, salary, start date, hours/week, and be signed",
    "LMIA (Labour Market Impact Assessment) number — if your position requires one; OR LMIA-exempt supporting letter (CUSMA, Intra-Company Transfer, etc.)",
    "Valid passport (must cover entire work permit period)",
    "Educational credentials relevant to the position",
    "Work experience proof — previous employment letters",
    "Proof of sufficient funds",
    "Biometrics (if first application or expired)",
    "Medical exam (for certain occupations like healthcare or working with children/vulnerable persons)",
    "Two passport-style photos",
  ],
  VISITOR_VISA: [
    "Valid passport — at least 6 months validity beyond your intended stay",
    "Two photos — IRCC-compliant (35mm × 45mm, plain white background)",
    "Proof of financial means — bank statements (last 3-6 months), employment letter confirming salary and approved leave",
    "Travel itinerary — flights, hotel bookings, or itinerary letter",
    "Letter of invitation — if visiting family/friends in Canada (include their PR/citizenship status and contact details)",
    "Previous travel history — US visa, Schengen visas, or stamps in passport (strengthens application)",
    "Proof of strong ties to home country — property deeds, employment letter, family proof showing you will return",
    "Completed Visitor Visa Application — IMM 5257",
    "Biometrics (if applicable)",
  ],
  FAMILY_SPONSORSHIP: [
    "Sponsor: Proof of Canadian status — citizenship certificate or PR card (front and back)",
    "Sponsor: Proof of income — Notice of Assessment (NOA) for last 3 years + T1 General",
    "Sponsor: IMM 1344 — Application to Sponsor, Sponsorship Agreement and Undertaking",
    "Sponsor: IMM 5481 — Sponsorship Evaluation",
    "Sponsored person: Valid passport (all pages)",
    "Official marriage certificate (apostilled or notarized if not in English/French)",
    "Proof of relationship — minimum 20 photos together, communication records (texts, calls, emails), joint financial accounts/lease/bills",
    "Relationship Questionnaire (both partners complete separately) — IMM 5532",
    "Police certificates — from every country both parties lived in for 6+ months since age 18",
    "Medical exam from a designated IRCC panel physician",
    "Biometrics",
    "Two passport-style photos per applicant",
  ],
  SPOUSAL_SPONSORSHIP: [
    "Sponsor: Proof of Canadian status — citizenship certificate or PR card",
    "Sponsor: IMM 1344 — Application to Sponsor",
    "Sponsor: IMM 5481 — Sponsorship Evaluation",
    "Sponsored spouse: Valid passport (all pages)",
    "Official marriage certificate (apostilled/notarized)",
    "Proof of genuine relationship — 20+ photos, communication history, shared accounts/lease/bills",
    "Relationship Questionnaire IMM 5532 (both complete separately in private)",
    "Police certificates from all countries of residence since age 18",
    "Medical exam from designated IRCC physician",
    "Biometrics",
    "Two passport-style photos",
  ],
  SPOUSAL_OWP: [
    "Valid passport",
    "Marriage certificate or proof of common-law relationship (12 months cohabitation proof)",
    "Proof of your spouse/partner's status in Canada — work permit, study permit, or PR card",
    "Copy of your spouse/partner's work permit or confirmation of employer and NOC (for spouses of skilled workers)",
    "Proof of relationship — photos, communication records",
    "Two passport-style photos",
    "Biometrics (if applicable)",
  ],
  CITIZENSHIP: [
    "Current Permanent Resident (PR) card — front and back",
    "Valid passport or travel document (all passports issued in last 5 years)",
    "Physical Presence Calculation — travel history showing 1,095 days in Canada within last 5 years",
    "Proof of tax filing — Notice of Assessment (NOA) for at least 3 years within the 5-year period",
    "Language proof (if age 18-54) — CLB 4 in English or French: IELTS, CELPIP, TEF Canada, or TCF Canada",
    "Two passport-style photos (per IRCC specs)",
    "Criminal record check (police certificate) — only if requested by IRCC",
    "Completed IMM 0002E — Application for Canadian Citizenship (Adult)",
    "Study Guide: 'Discover Canada — The Rights and Responsibilities of Citizenship'",
  ],
  SUPER_VISA: [
    "Invitation letter from your Canadian child or grandchild — must include: their address, relationship to you, how long you're welcome to stay, and their financial commitment to support you",
    "Proof of your host's relationship to you — birth certificate, adoption papers",
    "Proof your host meets LICO (Low Income Cut-Off) — Notice of Assessment (NOA), T4, or recent pay stub",
    "Canadian travel medical insurance — minimum $100,000 coverage, valid for at least 1 year from a Canadian insurer (Manulife, Sun Life, Blue Cross, etc.)",
    "Valid passport (min 6 months validity)",
    "Visitor Visa Application — IMM 5257",
    "Two passport-style photos",
    "Bank statements from home country showing financial stability",
    "Proof of ties to home country — property, employment, family",
    "Biometrics (if applicable)",
  ],
  TRP: [
    "Valid passport",
    "Written explanation of why you need to enter Canada despite being inadmissible",
    "Supporting documents justifying your reason (e.g. medical appointment letters, conference invitation, family emergency proof)",
    "Evidence of steps taken toward rehabilitation (if criminal inadmissibility)",
    "Police certificate and court records related to any inadmissibility",
    "Proof you will leave Canada within the requested period",
    "Two passport-style photos",
  ],
  REFUGEE: [
    "Identity documents — passport, national ID, birth certificate, any available identification",
    "Evidence of persecution or risk — police reports, court documents, medical records, threatening letters, news articles",
    "Personal narrative statement — detailed chronological account of why you cannot return home",
    "Basis of Claim Form (BOC) — IMM 5856 (must be submitted within 15 days of claim)",
    "Evidence of country conditions — UNHCR reports, State Department reports, human rights organization reports",
    "List of witnesses (if any)",
    "Two passport-style photos",
  ],
  PRRA: [
    "Completed PRRA Application Form — IMM 5508 (must be submitted within 15 days of receiving PRRA notice)",
    "Personal narrative / written submissions — detailed explanation of new risks or evidence not considered in the original refugee hearing",
    "New evidence only — evidence that arose after or was not reasonably available at the time of your refugee hearing (PRRA is not a re-hearing)",
    "Country condition evidence — current UNHCR reports, human rights organization reports, news articles showing ongoing risk",
    "Police reports, threatening letters, or affidavits from witnesses in your home country",
    "Medical or psychological assessment (if risk is related to health or persecution trauma)",
    "Evidence of personal targeting — documentation showing you specifically are at risk",
    "Any removal order or deportation notice you have received",
    "Valid identity documents (passport, national ID, or any available ID)",
  ],
  HC: [
    "Completed H&C Application — IMM 5291 (Application to Remain in Canada as a Permanent Resident)",
    "Personal narrative / written submissions — explaining establishment in Canada, hardship if removed, best interests of any children",
    "Proof of establishment in Canada — employment letters, tax returns (NOA), bank statements, lease agreements, community involvement letters",
    "Employment history — reference letters, pay stubs, T4 slips, Record of Employment",
    "Proof of community ties — volunteer work, religious community, associations, support letters from community members",
    "Best Interests of the Child (BIOC) — school records, birth certificates, letters from teachers/doctors if children are involved",
    "Medical evidence — doctor letters, psychological assessments showing hardship of removal",
    "Country conditions evidence — showing hardship or risk upon return",
    "Family ties in Canada — proof of relationships (marriage certificate, birth certificates, statutory declarations)",
    "Evidence of hardship if removed — documentation of conditions in home country affecting you specifically",
    "Police certificates from all countries of residence since age 18",
    "Two passport-style photos",
    "Valid identity documents",
  ],
  VULNERABLE_WORKER: [
    "Evidence of the abuse/exploitation experienced",
    "Police report or victim services report (if available)",
    "Medical records or psychological assessment (if applicable)",
    "Support letters from shelters, social workers, or advocacy organizations",
    "Valid passport or any available identity documents",
    "Proof of current employment situation",
    "Two passport-style photos",
  ],
  LMIA_BASED_WORK_PERMIT: [
    "Job offer letter on employer letterhead — position title, NOC code, salary, start date, hours/week, signed by employer",
    "Positive LMIA (Labour Market Impact Assessment) — issued by ESDC, include LMIA number and employer confirmation letter",
    "Valid passport (must cover entire requested work permit period)",
    "Educational credentials relevant to the position",
    "Previous employment reference letters (same NOC category)",
    "Proof of qualifications — degrees, diplomas, trade certificates, professional licenses",
    "Biometrics (if first application or expired)",
    "Two passport-style photos",
    "Medical exam (if working in healthcare, childcare, or with vulnerable persons)",
  ],
  LMIA_EXEMPT_WORK_PERMIT: [
    "Valid passport (must cover entire work permit period)",
    "Job offer letter on employer letterhead — NOC code, salary, start date, duration",
    "LMIA exemption support letter or documentation — specify the exemption code (C11, C12, C20, R204, etc.)",
    "Intra-Company Transfer: proof of company relationship (org chart, ownership structure), job description",
    "CUSMA/USMCA (if applicable): proof of citizenship (US/Mexico), relevant degree/credentials",
    "International Agreement (if applicable): proof of treaty eligibility",
    "Employer Portal offer of employment number (OE number from IRCC Employer Portal)",
    "Biometrics (if first application or expired)",
    "Two passport-style photos",
  ],
  BUSINESS_INVESTMENT: [
    "Valid passport (all pages, min 6 months validity)",
    "Business plan — minimum 15 pages, covering executive summary, market analysis, operations, financial projections (3-5 years), job creation plan",
    "Proof of net worth — audited financial statements, tax returns (last 3 years), bank statements",
    "Source of funds documentation — business ownership proof, sale agreements, investment portfolios",
    "Business ownership proof — incorporation documents, share certificates, shareholder agreements",
    "Previous business experience — reference letters, business registration documents, contracts",
    "Provincial nomination letter (if applying under PNP Business stream)",
    "Educational credentials (degree, diploma, or professional certification)",
    "Police certificates from all countries of residence since age 18",
    "Medical exam from designated IRCC panel physician",
    "Two passport-style photos",
    "Biometrics",
  ],
  RESTORATION_VISITOR: [
    "Completed application to restore status as a visitor — IMM 5708 (Application to Change Conditions, Extend My Stay or Remain in Canada as a Visitor)",
    "Valid passport (must be valid for the entire period you are requesting to remain in Canada)",
    "Copy of your most recent visitor record or entry stamp showing when your authorized stay expired",
    "Explanation letter — written statement explaining why you overstayed and why restoration should be granted (must show it was not intentional and you maintained compliance otherwise)",
    "Proof you have maintained the conditions of your original visitor status (e.g. did not work or study without authorization)",
    "Proof of financial support — recent bank statements (last 3-6 months) showing sufficient funds to support your stay",
    "Employment letter or proof of financial means from a supporting family member (if applicable)",
    "Travel itinerary or letter confirming you intend to leave Canada before the newly requested authorized period expires",
    "Proof of ties to your home country — employment letter, property ownership, family proof showing intention to return",
    "Previous immigration documents — all previous visas, study/work permits, visitor records, or TRPs",
    "Two passport-style photos — IRCC compliant (35mm × 45mm, plain white background)",
    "Biometrics (if first application or biometrics have expired)",
    "Application fee payment receipt — Restoration fee: $229 CAD + Visitor Record fee (if requesting extension simultaneously)",
    "Note: Application MUST be submitted within 90 days of the date your status expired. Applications submitted after 90 days are not eligible for restoration.",
  ],
  OTHER: [
    "Valid passport with at least 6 months validity",
    "Two passport-style photos meeting IRCC specifications",
    "Supporting documents relevant to your specific application",
    "Proof of identity and civil status",
    "Police certificates from countries of residence",
    "Completed application forms as directed by your RCIC",
  ],
};

export const CASE_TYPE_LABELS: Record<string, string> = {
  CITIZENSHIP:            "Canadian Citizenship",
  PNP:                    "Provincial Nominee Program (PNP)",
  EXPRESS_ENTRY:          "Express Entry (Federal Skilled Worker / CEC / FST)",
  VULNERABLE_WORKER:      "Vulnerable Worker Open Work Permit",
  SPOUSAL_OWP:            "Spousal Open Work Permit",
  STUDY_PERMIT:           "Study Permit",
  SPOUSAL_SPONSORSHIP:    "Spousal Sponsorship",
  FAMILY_SPONSORSHIP:     "Family Sponsorship",
  SUPER_VISA:             "Super Visa (Parent / Grandparent)",
  VISITOR_VISA:           "Visitor Visa (Temporary Resident Visa)",
  BUSINESS_INVESTMENT:    "Business Investment Program",
  LMIA_EXEMPT_WORK_PERMIT:"LMIA Exempt Work Permit",
  LMIA_BASED_WORK_PERMIT: "LMIA Based Work Permit",
  RESTORATION_VISITOR:    "Restoration of Status – Visitor",
  TRP:                    "Temporary Resident Permit (TRP)",
  REFUGEE:                "Refugee / Protected Persons",
  PRRA:                   "PRRA – Pre-Removal Risk Assessment",
  HC:                     "H&C – Humanitarian and Compassionate",
  OTHER:                  "Other / Custom",
};
