// ═══════════════════════════════════════════════════════════════════════════
// CLIENT-FACING document checklists — safe to share outside the office.
// Deliberately EXCLUDES IRCC form numbers (IMM ___), NOC codes, LMIA/OE
// numbers, and internal stream codes. Wording follows current IRCC document
// requirements (2025–2026). Keys align with Case.caseType (+ PGWP extra).
// ═══════════════════════════════════════════════════════════════════════════

export const CLIENT_CHECKLISTS: Record<string, string[]> = {
  EXPRESS_ENTRY: [
    "🛂 Passport — valid for at least 6 months beyond your planned entry date (all pages, including blank ones)",
    "🗣️ Language test results — IELTS General or CELPIP (English), or TEF/TCF Canada (French) — results less than 2 years old",
    "🎓 Educational Credential Assessment (ECA) — if your education is from outside Canada (e.g., WES, IQAS, ICAS)",
    "💼 Work experience letters — on company letterhead for EVERY job in the last 10 years: job title, duties, hours/week, salary, employment dates, signed by HR or manager",
    "💰 Proof of settlement funds — official bank letters/statements for the last 6 months showing available funds (not needed if you have a valid Canadian job offer or are working in Canada)",
    "🚔 Police certificates — from every country you lived in for 6+ months since age 18",
    "🩺 Upfront medical exam — from an IRCC-approved panel physician (valid for 12 months)",
    "📷 Passport-style photos — 35mm × 45mm, plain white background, taken within last 6 months",
    "💍 If married / common-law: partner's passport, language test, ECA, police certificate, and proof of relationship (marriage certificate or 12-month cohabitation proof)",
    "👶 Children's documents (if applicable): birth certificates, custody/adoption papers",
    "🏅 Provincial nomination certificate (if a province has nominated you)",
    "📄 Any previous Canadian visas, permits, or refusal letters",
  ],
  PNP: [
    "🏅 Provincial nomination certificate or approval letter from the province",
    "🛂 Passport — valid for at least 6 months beyond your planned entry date (all pages)",
    "🗣️ Language test results — IELTS/CELPIP (English) or TEF/TCF Canada (French), less than 2 years old",
    "🎓 Educational Credential Assessment (ECA) — for education completed outside Canada",
    "💼 Work experience letters — on company letterhead: job title, duties, hours/week, salary, dates, signed",
    "📄 Valid job offer letter from your Canadian employer (if your stream requires one)",
    "💰 Proof of settlement funds — recent official bank statements",
    "🚔 Police certificates — every country you lived in for 6+ months since age 18",
    "🩺 Upfront medical exam — from an IRCC-approved panel physician",
    "📷 Passport-style photos — 35mm × 45mm, plain white background",
    "💍 Spouse/partner documents (if applicable): passport, language test, police certificate, relationship proof",
    "👶 Children's documents (if applicable): birth certificates, custody papers",
  ],
  STUDY_PERMIT: [
    "🎓 Letter of Acceptance from a Canadian school (must be on the official Designated Learning Institutions list)",
    "🏛️ Provincial Attestation Letter (PAL) — your school's admissions office issues this; required for most applicants",
    "🛂 Passport — valid for your whole study period plus 90 days (all pages)",
    "💰 Proof of funds — tuition payment proof + living costs (about CAD $22,895 per year outside Quebec) via bank statements, GIC certificate, or education loan approval",
    "📝 Statement of Purpose — why this program and school, how it fits your career, and your plan after graduation",
    "📚 Academic documents — transcripts, diplomas, and certificates from your previous school/college/university",
    "🗣️ Language test results (if your school requires them) — IELTS/TOEFL/PTE or DELF/DALF",
    "🏠 Proof of ties to your home country — employment letter, business/property ownership, family responsibilities",
    "🚔 Police certificate (if requested)",
    "🩺 Medical exam — from an IRCC-approved panel physician (required if you lived in certain countries or for some programs)",
    "📷 Passport-style photos — 35mm × 45mm, plain white background",
    "📄 Previous Canadian visas or permits (if any) and any prior refusal letters",
  ],
  PGWP: [
    "🎓 Final transcripts and official completion letter/degree from your Canadian school",
    "🛂 Passport — valid for the length of permit you are requesting (all pages)",
    "📋 Your study permit (and any previous permits)",
    "🗣️ Language test results — English or French, less than 2 years old (required for most graduates)",
    "📷 Passport-style photos — 35mm × 45mm, plain white background",
    "💰 Proof of funds for your stay in Canada",
    "🩺 Medical exam (if required for your occupation or travel history)",
  ],
  WORK_PERMIT: [
    "📄 Job offer letter — on employer letterhead: job title, salary, start date, hours per week, signed by the employer",
    "🛂 Passport — valid for your whole work period (all pages)",
    "🎓 Education documents — degrees, diplomas, or certificates relevant to the job",
    "💼 Work experience letters from previous employers — job title, duties, dates",
    "📜 Professional licences or trade certificates (if your job needs them)",
    "💰 Proof of funds to support yourself (and family) in Canada",
    "🚔 Police certificates (if requested)",
    "🩺 Medical exam — required for healthcare, childcare, agriculture, and some other jobs",
    "📷 Passport-style photos — 35mm × 45mm, plain white background",
    "💍 Family member documents (if they are applying with you): passports, relationship proof",
  ],
  VISITOR_VISA: [
    "🛂 Passport — valid for at least 6 months beyond your trip (all pages)",
    "💰 Proof of funds — bank statements (last 4–6 months), fixed deposits, or sponsor's financials",
    "💼 Employment proof — letter from employer stating your salary, position, and approved leave dates; business owners: registration + tax returns",
    "✈️ Travel plans — flight reservation, hotel bookings, or a day-by-day itinerary",
    "💌 Invitation letter — if staying with family/friends in Canada (include their status in Canada, address, and phone)",
    "🌍 Travel history — previous visas (US, UK, Schengen, etc.) and passport stamps",
    "🏠 Proof of ties to home country — property documents, family responsibilities, employment/business you will return to",
    "🚔 Police certificate (only if requested)",
    "📷 Passport-style photos — 35mm × 45mm, plain white background",
  ],
  SUPER_VISA: [
    "💌 Invitation letter from your child/grandchild in Canada — including their address, your relationship, length of stay, and their promise of financial support",
    "👶 Proof of relationship — your child's birth certificate showing they are your child",
    "💰 Proof your child/grandchild meets the income requirement — their latest tax assessment (NOA) or pay stubs",
    "🏥 Canadian medical insurance — minimum CAD $100,000 coverage for at least 1 year from a Canadian insurance company",
    "🩺 Immigration medical exam — from an IRCC-approved panel physician",
    "🛂 Passport — valid at least 6 months beyond your planned entry (all pages)",
    "💰 Your own financial documents — bank statements from your home country",
    "🏠 Proof of ties to home country — property, family, or reasons to return",
    "📷 Passport-style photos — 35mm × 45mm, plain white background",
  ],
  SPOUSAL_SPONSORSHIP: [
    "💍 Marriage certificate (official translation if not in English/French) OR proof of 12 months living together (common-law)",
    "🛂 Passport — for the applicant (all pages); sponsor's ID too",
    "📸 Relationship evidence — photos together over time (wedding, family, travel), chat/call screenshots, travel together, joint bank accounts, leases or bills in both names",
    "📝 Relationship questionnaire — each partner completes separately and privately (we will provide it)",
    "💰 Sponsor's financial documents — tax assessments for the last year (income requirement is flexible for spousal cases, but must not be receiving social assistance except disability)",
    "🛂 Sponsor's Canadian status proof — passport, PR card, or citizenship certificate",
    "🚔 Police certificates — applicant: every country lived in for 6+ months since age 18; sponsor: if requested",
    "🩺 Medical exam — applicant only, from an IRCC-approved panel physician",
    "📷 Passport-style photos — for both applicant and sponsor",
    "👶 Children's documents (if applicable): birth certificates, custody/adoption papers, school records",
    "📄 Previous marriage documents (if applicable): divorce certificate or death certificate of former spouse",
  ],
  FAMILY_SPONSORSHIP: [
    "🛂 Sponsor's Canadian status proof — citizenship certificate or PR card (both sides)",
    "💰 Sponsor's income proof — tax assessments (NOA) for the last 3 taxation years (required for parents/grandparents)",
    "📝 Signed sponsorship undertaking forms (we will prepare these for signature)",
    "🛂 Applicant's passport — all pages",
    "👶 Proof of relationship — birth certificates linking sponsor and applicant(s)",
    "🚔 Police certificates — every country lived in for 6+ months since age 18",
    "🩺 Medical exam — from an IRCC-approved panel physician",
    "📷 Passport-style photos — each applicant",
    "💍 Applicant's marital status documents — marriage/divorce certificates (if applicable)",
    "👶 Dependent children's documents — birth certificates, custody papers",
  ],
  SPOUSAL_OWP: [
    "💍 Marriage certificate OR proof of 12 months living together (common-law)",
    "🛂 Your passport (all pages)",
    "📄 Your spouse/partner's status in Canada — work permit, study permit, or PR card copy",
    "💼 Your spouse/partner's job proof — employment letter or pay stubs showing their occupation",
    "📸 Relationship proof — photos, joint accounts, shared lease or bills",
    "📷 Passport-style photos — 35mm × 45mm, plain white background",
  ],
  CITIZENSHIP: [
    "🪪 Permanent Resident (PR) card — copy of both sides",
    "🛂 All passports held in the last 5 years (all pages, even expired)",
    "📅 Travel history — complete list of trips outside Canada in the last 5 years (dates in/out) to show 1,095 days of physical presence",
    "💰 Tax filing proof — tax assessments for at least 3 of the last 5 years",
    "🗣️ Language proof (ages 18–54) — results showing CLB 4 or higher in English or French",
    "📷 Passport-style photos — per IRCC specifications",
    "🚔 Police certificate (only if requested)",
    "📚 Study guide — 'Discover Canada' (we will send it — needed for the citizenship test)",
  ],
  TRP: [
    "🛂 Passport — valid beyond your planned stay (all pages)",
    "📝 Written explanation — why you need to come to Canada now despite your inadmissibility",
    "📎 Supporting proof — medical appointment letters, event invitations, family emergency documents (whatever justifies the visit)",
    "🚔 Police certificates and court records — related to your inadmissibility",
    "📈 Evidence of rehabilitation — completed programs, employment stability, community involvement (for criminal inadmissibility)",
    "✈️ Proof you will leave Canada at the end of your visit — return ticket, job letter, family obligations",
    "📷 Passport-style photos — 35mm × 45mm, plain white background",
  ],
  REFUGEE: [
    "🪪 Identity documents — passport, national ID, birth certificate, any available identification for you and your family",
    "📄 Evidence of your risk — police reports, court documents, medical reports, threatening letters/messages, news articles about you",
    "📝 Your personal story — a detailed, chronological account of what happened to you and why you cannot return home safely",
    "🌍 Country condition evidence — reports about the situation in your home country (we will help gather these)",
    "👥 Witness list — names and contact of anyone who can support your claim (if any)",
    "📷 Passport-style photos — 35mm × 45mm, plain white background",
    "⏰ Important: the Basis of Claim form has strict deadlines — bring everything you have to our first meeting",
  ],
  PRRA: [
    "📄 The PRRA letter you received from IRCC (with your deadline — it is usually very short)",
    "📝 New written submissions — your story plus anything new that happened after your refugee hearing",
    "🆕 New evidence only — documents that did not exist or were not available at your hearing",
    "🌍 Updated country condition reports — showing current risk in your home country",
    "🚔 Police reports, threats, or witness statements — specific to you",
    "🩺 Medical or psychological reports (if your risk relates to health or trauma)",
    "📄 Any removal order or deportation letter you received",
    "🪪 Identity documents — passport, national ID, or any available ID",
  ],
  HC: [
    "📝 Your personal story — how you established your life in Canada, what hardship you or your family would face if removed",
    "💼 Establishment proof — employment letters, pay stubs, tax assessments, business records",
    "🏠 Life in Canada — lease/mortgage, bank accounts, volunteer and community letters, memberships",
    "👶 Children's best-interest documents — school records, letters from teachers/doctors, birth certificates",
    "🩺 Medical reports — conditions that would worsen if removed (yours or family members')",
    "🌍 Hardship in home country — evidence of conditions affecting you specifically (medical access, safety, discrimination)",
    "👨‍👩‍👧 Family ties in Canada — marriage/birth certificates, letters of support from family and community",
    "🚔 Police certificates — every country lived in for 6+ months since age 18",
    "🛂 Passport and all identity documents",
    "📷 Passport-style photos — 35mm × 45mm, plain white background",
  ],
  VULNERABLE_WORKER: [
    "📄 Evidence of the abuse or exploitation — messages, emails, witness names, photos of conditions",
    "🚔 Police report or victim-services report (if you made one)",
    "🩺 Medical or psychological records (if applicable)",
    "🤝 Support letters — shelters, social workers, or advocacy organizations helping you",
    "🛂 Passport or any identity documents you have",
    "💼 Proof of your current employment situation — pay stubs, schedules, employer name and address",
    "📷 Passport-style photos — 35mm × 45mm, plain white background",
  ],
  LMIA_BASED_WORK_PERMIT: [
    "📄 Job offer letter — on employer letterhead: job title, salary, start date, hours per week, signed",
    "📋 Employer's government approval for hiring you (your employer provides this — ask them for a copy)",
    "🛂 Passport — valid for your whole work period (all pages)",
    "🎓 Education documents — degrees, diplomas, or certificates relevant to the job",
    "💼 Work experience letters from previous employers in the same field",
    "📜 Trade certificates or professional licences (if your job requires them)",
    "🩺 Medical exam — required for healthcare, childcare, agriculture, and similar jobs",
    "🚔 Police certificates (if requested)",
    "📷 Passport-style photos — 35mm × 45mm, plain white background",
  ],
  LMIA_EXEMPT_WORK_PERMIT: [
    "📄 Job offer letter — on employer letterhead: job title, salary, start date, duration, signed",
    "📋 Employer's exemption confirmation — your employer submits this through the employer portal and shares the confirmation number with us",
    "🛂 Passport — valid for your whole work period (all pages)",
    "🎓 Education and credentials relevant to the position",
    "💼 Work experience letters — especially for the same type of role",
    "🏢 If transferring within your company: proof the companies are related (ownership structure, company documents)",
    "📷 Passport-style photos — 35mm × 45mm, plain white background",
    "💰 Proof of funds for your stay",
    "🩺 Medical exam (if required for your occupation)",
  ],
  BUSINESS_INVESTMENT: [
    "🛂 Passport — all pages, valid at least 6 months beyond planned entry",
    "📊 Business plan — market analysis, operations, 3–5 year financial projections, job creation plan (we will guide the format)",
    "💰 Proof of net worth — audited financial statements, tax returns (last 3 years), bank statements",
    "🧾 Source of funds — how you earned your money: business ownership documents, sale agreements, investment records",
    "🏢 Business ownership proof — registration documents, share certificates, partnership agreements",
    "💼 Business experience — reference letters, contracts, licences",
    "🏅 Provincial nomination letter (if a province nominated you)",
    "🎓 Educational credentials",
    "🚔 Police certificates — every country lived in for 6+ months since age 18",
    "🩺 Medical exam — from an IRCC-approved panel physician",
    "📷 Passport-style photos — 35mm × 45mm, plain white background",
  ],
  RESTORATION_VISITOR: [
    "🛂 Passport — valid for the entire period you are requesting to stay (all pages)",
    "📄 Your most recent visitor record, permit, or entry stamp showing when your status ended",
    "📝 Explanation letter — why your status lapsed, why it was not intentional, and why you should be restored (we will help you draft this)",
    "💰 Proof of funds — recent bank statements (last 3–6 months)",
    "🏠 Proof of ties to home country — employment letter, property, family responsibilities",
    "✈️ Confirmation you plan to leave before the new authorized period ends",
    "📄 All previous Canadian immigration documents — visas, permits, visitor records",
    "📷 Passport-style photos — 35mm × 45mm, plain white background",
    "⏰ Critical: restoration is only possible within 90 days of your status ending — contact us immediately if you are close to this deadline",
  ],
  OTHER: [
    "🛂 Passport — valid at least 6 months beyond your planned stay (all pages)",
    "📷 Passport-style photos — 35mm × 45mm, plain white background",
    "🪪 Proof of identity and marital status — national ID, marriage/divorce certificates",
    "🚔 Police certificates — from countries where you lived",
    "💰 Proof of financial support — recent bank statements",
    "📎 Any documents specific to your situation — your consultant will give you a personalized list at your first meeting",
  ],
};

/** Extra label for the PGWP client checklist (not a CaseType). */
export const CLIENT_CHECKLIST_LABELS: Record<string, string> = {
  PGWP: "Post-Graduation Work Permit",
};

/** WhatsApp-ready plain-text version of a checklist. */
export function clientChecklistAsText(
  type: string,
  opts: { firmName?: string; label?: string; link?: string } = {},
): string {
  const items = CLIENT_CHECKLISTS[type] ?? CLIENT_CHECKLISTS.OTHER;
  const label = opts.label ?? CLIENT_CHECKLIST_LABELS[type] ?? type.replace(/_/g, " ");
  const header = opts.firmName
    ? `*${opts.firmName}* — Document Checklist\n*${label}*\n\n`
    : `*Document Checklist — ${label}*\n\n`;
  const body = items.map((item, i) => `${i + 1}. ${item}`).join("\n");
  const footer = `\n\n✅ Gather these and upload them through your secure client portal (or send them to us). Originals or clear scans both work to start.\n${opts.link ? `\n🔗 ${opts.link}\n` : ""}_Please remove form numbers from your mind — we prepare all government forms for you._`;
  return header + body + footer;
}
