export interface KbEntry {
  id: string;
  title: string;
  category: string;
  keywords: string[];
  content: string;
  citations: { section: string; url?: string }[];
}

const entries: KbEntry[] = [
  {
    id: "ee-overview",
    title: "Express Entry Overview",
    category: "express-entry",
    keywords: ["express entry", "ee", "pr", "permanent residence", "quick entry", "federal"],
    content: "Express Entry is Canada's flagship economic immigration system launched in 2015, managed under IRPA ss. 10.1-10.6 and IRPR ss. 75-116. It manages applications for three federal programs: the Federal Skilled Worker Program (FSW), the Canadian Experience Class (CEC), and the Federal Skilled Trades Program (FST). Candidates create an online profile and are ranked using the Comprehensive Ranking System (CRS). The highest-ranked candidates receive an Invitation to Apply (ITA) through periodic draws. Once invited, candidates have 60 days to submit a complete application. IRCC targets processing 80% of applications within 6 months.",
    citations: [
      { section: "IRPR ss. 75-116", url: "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2002-227/" },
      { section: "IRPA ss. 10.1-10.6" },
    ],
  },
  {
    id: "ee-fsw",
    title: "Federal Skilled Worker Program (FSW)",
    category: "express-entry",
    keywords: ["fsw", "federal skilled worker", "skilled worker", "67 points", "six selection factors"],
    content: "The Federal Skilled Worker Program (FSW) is for skilled professionals with foreign work experience. Eligibility requires at least 67 points out of 100 on six selection factors: education (max 25), language ability (max 28), work experience (max 15), age (max 12), arranged employment (max 10), and adaptability (max 10). Applicants must have at least 1 year of continuous full-time skilled work experience (or equivalent part-time) in NOC TEER 0, 1, 2, or 3 within the last 10 years. Minimum CLB 7 in English or French is required. Proof of funds is required unless the applicant has a valid job offer or is already working in Canada.",
    citations: [
      { section: "IRPR ss. 75-83" },
      { section: "IRPR s. 76(1) – Selection Criteria" },
    ],
  },
  {
    id: "ee-cec",
    title: "Canadian Experience Class (CEC)",
    category: "express-entry",
    keywords: ["cec", "canadian experience", "canadian work experience", "express entry work"],
    content: "The Canadian Experience Class (CEC) is for individuals who have gained at least 1 year of skilled work experience in Canada within the 3 years before applying. Work must be in NOC TEER 0, 1, 2, or 3. For TEER 0 or 1, minimum CLB 7 is required. For TEER 2 or 3, minimum CLB 5 is required. Education is not a eligibility requirement for CEC, though points are awarded for education under CRS. No proof of funds is required. The work experience must have been obtained with proper temporary resident status and authorization.",
    citations: [
      { section: "IRPR ss. 87.1-91" },
      { section: "IRPR s. 87.1(2) – CEC Requirements" },
    ],
  },
  {
    id: "ee-fst",
    title: "Federal Skilled Trades Program (FST)",
    category: "express-entry",
    keywords: ["fst", "skilled trades", "tradesperson", "trades", "blue collar"],
    content: "The Federal Skilled Trades Program (FST) is for qualified skilled tradespersons. Eligibility requires at least 2 years of full-time work experience (or equivalent part-time) in a skilled trade within the 5 years before applying. The trades are organized under NOC TEER 2 and 3 major groups: Industrial, electrical and construction trades; Maintenance and equipment operation trades; Supervisors and technical occupations in natural resources and agriculture; Processing, manufacturing and utility supervisors and central control operators; Chefs and cooks; Butchers and bakers. Applicants must meet the job requirements for that trade as set out in the NOC, have a valid job offer of at least 1 year or a certificate of qualification from a provincial or territorial authority, and meet minimum CLB 5 for speaking/listening and CLB 4 for reading/writing.",
    citations: [
      { section: "IRPR ss. 92-101" },
      { section: "IRPR s. 93 – FST Requirements" },
    ],
  },
  {
    id: "crs-scoring",
    title: "Comprehensive Ranking System (CRS)",
    category: "express-entry",
    keywords: ["crs", "comprehensive ranking system", "score", "points", "ranking", "ita"],
    content: "The Comprehensive Ranking System (CRS) ranks Express Entry candidates out of a maximum of 1,200 points. Core/human capital factors (age, education, language, Canadian work experience) = max 500 points. Spouse factors (education, language, Canadian work experience) = max 40 points. Skill transferability (education + language, education + foreign work, foreign work + language, Canadian work + language) = max 100 points. Additional points: provincial nomination = 600, qualifying job offer = 50 or 200, Canadian education = 15 or 30, French language proficiency = 50, sibling in Canada = 15. Candidates with the highest CRS scores receive ITAs in periodic draws.",
    citations: [
      { section: "IRPR ss. 102-116" },
      { section: "IRPR s. 104 – CRS Point Grid" },
    ],
  },
  {
    id: "pnp-overview",
    title: "Provincial Nominee Programs (PNP)",
    category: "pnp",
    keywords: ["pnp", "provincial nominee", "nomination", "province", "territory", "pn"],
    content: "The Provincial Nominee Program (PNP) allows Canadian provinces and territories to nominate individuals for permanent residence who meet local economic needs. Each province operates its own streams: Ontario (OINP), British Columbia (BC PNP), Alberta (AAIP), Manitoba (MPNP), Saskatchewan (SINP), Nova Scotia (NSNP), New Brunswick (NBPNP), Newfoundland and Labrador (NLPNP), Prince Edward Island (PEI PNP), Yukon (YNP), Northwest Territories (NTNP). PNP has two pathways: Base (paper-based, processed outside Express Entry, takes 18-24 months) and Enhanced (linked to Express Entry, 600 CRS points added, processed within 6 months). Each stream has unique eligibility criteria.",
    citations: [
      { section: "IRPR ss. 61-73 – Provincial Nominees" },
      { section: "IRPA s. 87 – Provincial Nomination" },
    ],
  },
  {
    id: "pnp-oinp",
    title: "Ontario Immigrant Nominee Program (OINP)",
    category: "pnp",
    keywords: ["oinp", "ontario", "ontario pnp", "ontario nominee", "ontario immigrant"],
    content: "The Ontario Immigrant Nominee Program (OINP) operates several streams: Human Capital Priorities (HCP) – searches Express Entry for candidates in targeted occupations, requires CRS 350+ and CLB 7; French-Speaking Skilled Worker – requires CLB 7 French and CLB 6 English; Skilled Trades – for Express Entry candidates with 1+ year Ontario skilled trades experience; Master's Graduate – for recent Ontario master's graduates, no job offer needed; PhD Graduate – for Ontario PhD graduates; Employer Job Offer streams (Foreign Worker, International Student, In-Demand Skills). Ontario regularly issues targeted Notifications of Interest (NOIs) to Express Entry candidates.",
    citations: [
      { section: "OINP Guidelines – O. Reg. 422/17" },
    ],
  },
  {
    id: "pnp-bcpnp",
    title: "British Columbia PNP (BC PNP)",
    category: "pnp",
    keywords: ["bc pnp", "british columbia", "bc nominee", "bc immigration"],
    content: "British Columbia's Provincial Nominee Program (BC PNP) operates through the Skills Immigration and Express Entry BC streams. Key streams: Skilled Worker – requires a valid job offer in BC in a skilled occupation; Health Authority – for physicians, nurses, and allied health professionals; International Graduate – for recent graduates of Canadian or foreign institutions with a BC job offer; International Post-Graduate – for graduates of BC master's/PhD programs in natural, applied, or health sciences (no job offer needed); Entry Level and Semi-Skilled – for workers in tourism/hospitality, food processing, and long-haul trucking. The BC PNP uses a points-based registration system (Skills Immigration Registration System or SIRS) with regular draws.",
    citations: [
      { section: "BC PNP Program Guide" },
    ],
  },
  {
    id: "study-permit",
    title: "Study Permits",
    category: "study-permit",
    keywords: ["study permit", "student", "international student", "dli", "designated learning", "college", "university"],
    content: "A study permit is required for programs longer than 6 months at a Designated Learning Institution (DLI). Requirements: acceptance letter from a DLI, proof of sufficient funds (tuition + $20,635 living costs + return transportation for 2024), no criminal or immigration record, medical exam if required, and intent to leave Canada after studies. Study permits are typically valid for the duration of the program plus 90 days. Off-campus work: up to 24 hours/week during academic sessions, full-time during breaks (IRPR s. 186(v)). Full-time students at DLIs may work off-campus without a separate work permit. Spouses of full-time students may be eligible for open work permits. PGWP eligibility requires continuous full-time enrollment in a program of at least 8 months at a DLI.",
    citations: [
      { section: "IRPR ss. 210-230 – Study Permits" },
      { section: "IRPR s. 186(v) – Off-Campus Work" },
      { section: "IRPR s. 205(c)(ii) – Off-Campus Work" },
    ],
  },
  {
    id: "pgwp",
    title: "Post-Graduation Work Permit (PGWP)",
    category: "study-permit",
    keywords: ["pgwp", "post graduation", "post-graduation", "graduate work permit", "graduation", "work after study"],
    content: "The Post-Graduation Work Permit (PGWP) allows graduates of eligible Canadian DLIs to work in Canada after graduation. Eligibility: completed a program of at least 8 months at a DLI leading to a degree, diploma, or certificate, maintained continuous full-time enrollment (except final academic session), and applied within 180 days of receiving final marks or completion letter. PGWP length: programs 8 months to under 2 years = permit valid for same length as program; programs 2 years or more = 3-year PGWP. PGWP is an open work permit (no LMIA needed). PGWP holders can gain Canadian work experience eligible for CEC. PGWP can only be issued once per lifetime.",
    citations: [
      { section: "IRPR ss. 201-206 – Work Permits for Graduates" },
      { section: "IRPR s. 205(c)(ii) – Significant Benefit" },
    ],
  },
  {
    id: "work-permit-lmia",
    title: "LMIA-Based Work Permits",
    category: "work-permit",
    keywords: ["lmia", "labour market impact assessment", "employer specific", "closed work permit", "job offer"],
    content: "A Labour Market Impact Assessment (LMIA) is a document from Employment and Social Development Canada (ESDC) that confirms hiring a foreign worker will have a positive or neutral impact on the Canadian labour market. Employer-specific (closed) work permits require a positive LMIA, unless LMIA-exempt. LMIA processing: Global Talent Stream = 10 business days; High-Wage and Low-Wage streams = approximately 60 business days. The employer must pay the LMIA processing fee ($1,000 per position for most streams). Employer compliance: employers must maintain records, comply with wages/conditions, and may be subject to inspections. Dual intent: temporary and permanent residence can be pursued simultaneously.",
    citations: [
      { section: "IRPR ss. 200-209 – Work Permits" },
      { section: "IRPR ss. 203(1) – LMIA Requirement" },
      { section: "Immigration and Refugee Protection Regulations, Division 7" },
    ],
  },
  {
    id: "work-permit-lmia-exempt",
    title: "LMIA-Exempt Work Permits",
    category: "work-permit",
    keywords: ["lmia exempt", "open work permit", "international mobility", "c", "free trade", "intra-company", "ict"],
    content: "LMIA-exempt work permits fall under the International Mobility Program (IMP). Categories: C10 – significant benefit to Canada (e.g., intra-company transferees, entrepreneurs); C11 – reciprocal employment; C12 – spouses of skilled workers/students; C16 – USMCA/CUSMA professionals (NAFTA replacement); C20 – researchers, lecturers; C21 – post-graduation work permit holders; C41 – spouses of full-time international students; C42 – spouses of PGWP holders working in TEER 0/1/2/3; C43 – refugee claimants with positive eligibility; C47 – youth exchange programs (IEC). Open work permits are not tied to a specific employer. Employer-specific LMIA-exempt permits require an employer-specific exemption code and compliance fee ($230). Processing: IMP applications are typically processed within 60-120 days.",
    citations: [
      { section: "IRPR s. 205 – LMIA Exemptions" },
      { section: "IRPR ss. 204-207" },
      { section: "USMCA/CUSMA Chapter 16" },
    ],
  },
  {
    id: "spousal-owp",
    title: "Spousal Open Work Permit (SOWP)",
    category: "work-permit",
    keywords: ["sowp", "spousal", "spouse", "open work permit spouse", "spousal work permit"],
    content: "The Spousal Open Work Permit (SOWP) allows spouses of work permit holders and international students to work in Canada. For spouses of work permit holders: the work permit holder must be employed in TEER 0, 1, 2, or 3 and have at least 6 months remaining on their permit. For spouses of international students: the student must hold a valid study permit and be enrolled full-time at a DLI in a program leading to a degree or diploma at a university or college. As of 2024, spouses of international students in bachelor's, master's, and doctoral programs remain eligible. Spouses of students in other programs have restricted eligibility. The SOWP is generally valid for the same duration as the principal applicant's status and allows work for any employer.",
    citations: [
      { section: "IRPR s. 205(c)(ii) – Significant Benefit" },
      { section: "IRPR s. 205(c)(iii) – Significant Benefit (Spouses)" },
    ],
  },
  {
    id: "visitor-visa-trv",
    title: "Visitor Visa / Temporary Resident Visa (TRV)",
    category: "visitor",
    keywords: ["visitor visa", "trv", "temporary resident", "tourist", "visit canada", "visitor record"],
    content: "A Temporary Resident Visa (TRV) or eTA is required for foreign nationals visiting Canada, unless visa-exempt. Visa-required countries must apply for a TRV. Visa-exempt nationals need an eTA (Electronic Travel Authorization) when flying to Canada. TRV application requirements: valid passport, proof of sufficient funds for stay, ties to home country (employment, property, family), travel history, purpose of visit, and intent to leave Canada at end of authorized stay. Visitor Record: issued at entry or by application, allows stays of up to 6 months. Extensions can be applied for from within Canada before status expires. Super Visa: multi-entry visa for parents/grandparents of Canadian citizens/PRs, valid for up to 10 years, allowing stays of up to 5 years per entry. Requires proof of minimum income (LICO + 30%), Canadian insurance coverage ($100,000 minimum), and a signed invitation letter.",
    citations: [
      { section: "IRPR ss. 179-194 – Temporary Resident Visas" },
      { section: "IRPR s. 183 – Required Documentation" },
      { section: "IRPR s. 186 – Authorized Stays" },
    ],
  },
  {
    id: "sponsorship-spouse",
    title: "Spousal Sponsorship (Inland & Outland)",
    category: "family-sponsorship",
    keywords: ["spouse sponsorship", "spousal", "inland", "outland", "sponsor", "common law", "conjugal"],
    content: "Canadian citizens and permanent residents can sponsor their spouse, common-law partner, or conjugal partner for permanent residence. Eligibility: sponsor must be 18+, Canadian citizen or PR, not receiving social assistance (except disability), and able to demonstrate sufficient income to support the sponsored person (unless the sponsorship is for a spouse/partner without dependent children). Sponsored person: must be 18+ for spouse partner. Inland sponsorship: both sponsor and applicant live together in Canada; includes open work permit for applicant; processing time ~12-15 months. Outland sponsorship: applicant lives outside Canada (or can be inside); processing time ~10-12 months. Common-law partner: must have continuously cohabited for at least 12 months. Conjugal partner: for exceptional circumstances where cohabitation or marriage is not possible. The undertaking period is 3 years from the date the sponsored person becomes a PR.",
    citations: [
      { section: "IRPR ss. 116-145 – Family Class" },
      { section: "IRPR s. 130 – Sponsorship Requirements" },
      { section: "IRPR s. 132(1) – Undertaking Period" },
    ],
  },
  {
    id: "sponsorship-parent",
    title: "Parent and Grandparent Sponsorship (PGP)",
    category: "family-sponsorship",
    keywords: ["parent", "grandparent", "pgp", "sponsor parent", "parent sponsorship", "sponsorship parents"],
    content: "The Parents and Grandparents Program (PGP) allows Canadian citizens and PRs to sponsor their parents and grandparents for permanent residence. The program operates on a lottery/interest to sponsor system. IRCC issues invitations to apply to randomly selected sponsors from the pool of interest forms submitted during the annual intake window. Sponsor requirements: minimum income threshold (LICO + 30% for the 3 consecutive tax years before applying), must continue to meet LICO during processing. Undertaking period: 20 years (from Quebec: 10 years). As an alternative, the Super Visa allows parents and grandparents to visit for up to 5 years at a time and is valid for up to 10 years.",
    citations: [
      { section: "IRPR ss. 116-145 – Family Class" },
      { section: "IRPR s. 133(1)(j) – PGP Income Requirement" },
    ],
  },
  {
    id: "proof-of-funds",
    title: "Proof of Funds Requirements",
    category: "general",
    keywords: ["proof of funds", "funds", "financial", "settlement funds", "minimum funds", "pof"],
    content: "Proof of funds (POF) is required for FSW and FST programs in Express Entry (exempt for CEC and those with a valid job offer or authorized to work in Canada). POF amounts are updated annually by IRCC based on 50% of LICO (Low Income Cut-Off). As of 2024: 1 person = $14,690; 2 persons = $18,288; 3 persons = $22,483; 4 persons = $27,297; 5 persons = $30,690; 6 persons = $34,597; 7+ persons = $38,506. Funds must be readily available (cash, bank accounts, investments, not real estate) and unencumbered by debts. Funds can be in Canada or abroad. The applicant must be able to use the funds upon arrival. The 3-month average balance is commonly reviewed. Funds for spouses and dependent children are included.",
    citations: [
      { section: "IRPR s. 76(1)(b) – Financial Requirements" },
      { section: "IRPR s. 76(3) – Exemptions" },
    ],
  },
  {
    id: "biometrics",
    title: "Biometrics Requirements",
    category: "general",
    keywords: ["biometrics", "fingerprints", "photo", "bometric", "vfs", "service canada"],
    content: "Biometrics (fingerprints and photograph) are required for most immigration applications. Validity: 10 years from the date of enrolment. Applicants must give biometrics at a designated VAC (Visa Application Centre), Service Canada location, or US Application Support Center (for applicants in the US). Exemptions: citizens of visa-exempt countries applying for a study/work permit (unless TRV also required), children under 14, and applicants over 79. Biometrics fee: CAD $85 per person or $170 for a family of 2+ persons. Biometrics must be provided within 30 days of the biometric instruction letter (BIL).",
    citations: [
      { section: "IRPR ss. 12.1-12.8 – Biometrics" },
      { section: "IRPA s. 32(1) – Biometrics Regulations" },
    ],
  },
  {
    id: "language-requirements",
    title: "Language Requirements (IELTS, CELPIP, TEF)",
    category: "general",
    keywords: ["language", "ielts", "celpip", "tef", "clb", "nclc", "english", "french", "test score"],
    content: "Language proficiency is a core requirement for most economic immigration programs. Approved tests: IELTS General (English), CELPIP General (English), TEF Canada (French), TCF Canada (French). CLB (Canadian Language Benchmarks) equivalencies: CLB 4 = IELTS 4.0/4.5; CLB 5 = IELTS 5.0; CLB 6 = IELTS 5.5; CLB 7 = IELTS 6.0 (minimum for FSW, CEC TEER 0/1); CLB 8 = IELTS 6.5; CLB 9 = IELTS 7.0; CLB 10 = IELTS 7.5-8.0. Test results are valid for 2 years from the test date. For French: NCLC is the equivalent scale (Niveau de compétence linguistique canadien). Bilingual candidates can earn up to 50 additional CRS points for strong French ability (CLB 7+) combined with English (CLB 5+).",
    citations: [
      { section: "IRPR s. 78 – Language Proficiency" },
      { section: "IRPR s. 80 – Language Test Requirements" },
    ],
  },
  {
    id: "eca",
    title: "Educational Credential Assessment (ECA)",
    category: "general",
    keywords: ["eca", "education", "credential assessment", "degree evaluation", "wes", "ices", "comparative"],
    content: "An Educational Credential Assessment (ECA) is required for FSW program points for foreign education and for CRS points for education obtained outside Canada. Designated ECA organizations: WES (World Education Services), ICES (International Credential Evaluation Service), IQAS (International Qualifications Assessment Service), and several others. ECA processing time varies by organization (WES = approximately 30-35 business days). ECAs are valid for 5 years from the date of issue. The ECA report indicates the Canadian equivalency: secondary school, one-year program credential, two-year program credential, bachelor's degree, or master's/PhD.",
    citations: [
      { section: "IRPR s. 73(1) – Educational Requirements" },
      { section: "IRPR s. 75(2)(c) – ECA Requirement" },
    ],
  },
  {
    id: "citizenship",
    title: "Canadian Citizenship",
    category: "citizenship",
    keywords: ["citizenship", "citizen", "naturalization", "passport", "grant", "oath"],
    content: "Canadian citizenship can be obtained by grant (naturalization) or by birth. Grant requirements: permanent resident status with no unfulfilled conditions, physically present in Canada for at least 1,095 days (3 years) in the 5 years before application, filed income tax for at least 3 years within the 5-year period, pass a knowledge test (for ages 18-54), demonstrate language proficiency in English/French at CLB 4 or higher (for ages 18-54). Minors do not need to meet the physical presence requirement but must be PRs. Citizenship applications are processed in approximately 12-18 months. Dual citizenship is permitted in Canada. The citizenship ceremony involves taking the Oath of Citizenship. Processing fee: adults $630, minors $100 (includes right of citizenship fee).",
    citations: [
      { section: "Citizenship Act s. 5(1) – Grant of Citizenship" },
      { section: "Citizenship Act s. 5(1)(c) – Physical Presence" },
    ],
  },
  {
    id: "inland-processing",
    title: "Inland vs Outland Processing",
    category: "general",
    keywords: ["inland", "outland", "processing office", "visa office", "application processing", "cpco"],
    content: "Inland processing: applications submitted by applicants physically inside Canada are processed by IRCC's Case Processing Centre (CPC) in Canada (e.g., CPC-Ottawa, Edmonton). Outland processing: applications submitted by applicants outside Canada (or those who IRCC directs to a foreign visa office) are processed by visa offices abroad (e.g., London, Manila, New Delhi, Sydney, Paris). Processing times often differ significantly between inland and outland offices. Some programs restrict where you can apply. Spousal sponsorship offers both inland and outland pathways. Inland spousal applicants may apply for an open work permit. Outland processing may be faster in some cases and allows the applicant to travel during processing (though not recommended for inland applications).",
    citations: [
      { section: "IRPR ss. 69-73 – Application Processing" },
    ],
  },
  {
    id: "super-visa",
    title: "Super Visa (Parents and Grandparents)",
    category: "visitor",
    keywords: ["super visa", "supervisa", "parent", "grandparent", "10 year", "parent super visa"],
    content: "The Super Visa is a multi-entry visa for parents and grandparents of Canadian citizens or permanent residents. It allows stays of up to 5 years per entry (renewable without leaving Canada). Validity: up to 10 years. Requirements: child must meet minimum income threshold (LICO + 30% for the previous year), parent/grandparent must purchase private medical insurance from a Canadian insurer for at least $100,000 coverage for 1 year, proof of relationship (birth certificate, etc.), and signed invitation letter from the child in Canada. Letter of undertaking to provide financial support from the child is also required. The Super Visa is processed through regular TRV application channels with additional documentation.",
    citations: [
      { section: "IRPR s. 179 – TRV Provisions" },
      { section: "IRCC Policy – Super Visa Guidelines" },
    ],
  },
  {
    id: "maintained-status",
    title: "Maintained Status (Formerly Implied Status)",
    category: "general",
    keywords: ["maintained status", "implied status", "implied", "maintained", "overstay", "status restoration"],
    content: "Maintained status (formerly known as implied status) allows temporary residents to continue their authorized stay under the same conditions while IRCC processes their extension application, provided they applied BEFORE their status expired. Maintained status applies to: study permit extensions, work permit extensions, visitor record extensions. Condition: the applicant must have submitted a complete application before the expiry of their current status. It does NOT apply to: applications for a change in status (e.g., visitor to worker, visitor to student) unless authorized by policy, restoration applications, or applications submitted after status expiry. Restoration: available within 90 days of losing status for visitors, workers, and students (study permit restoration only within 90 days).",
    citations: [
      { section: "IRPR s. 186(1) – Maintained Status" },
      { section: "IRPR ss. 181-185 – Restoration" },
    ],
  },
  {
    id: "medical-exam",
    title: "Medical Exam Requirements",
    category: "general",
    keywords: ["medical", "exam", "medical exam", "doctor", "panel physician", "ime", "inadmissible", "health"],
    content: "Medical exams are required for most permanent residence applications and some temporary residence applications (study/work permits for programs over 6 months, or if coming from designated countries). Panel physicians are IRCC-approved doctors who perform immigration medical exams (IMEs). An IME includes: physical examination, chest X-ray (for ages 11+), blood tests (syphilis, HIV for ages 15+), and urinalysis (for ages 5+). Medical validity: 12 months from the date of exam. Medical inadmissibility: a foreign national may be inadmissible on health grounds if their condition would cause excessive demand (exceeding the cost threshold of approximately $28,200 CAD per year in 2025, updated annually) on health or social services (IRPA s. 38(1)(c)). Exemptions exist for refugees, protected persons, dependents, and certain sponsorship cases.",
    citations: [
      { section: "IRPA s. 38 – Medical Inadmissibility" },
      { section: "IRPR s. 30 – Medical Examination" },
    ],
  },
  {
    id: "police-certificate",
    title: "Police Certificates / Criminal Record Checks",
    category: "general",
    keywords: ["police certificate", "police clearance", "criminal record", "pcc", "background check", "rcmp"],
    content: "Police certificates are required for all permanent residence applicants aged 18+ and for certain temporary residence applications. Requirements: certificates from every country where the applicant has lived for 6+ months since age 18. Canadian police certificate: RCMP criminal record check (fingerprint-based) is typically not required upfront but may be requested during processing. Processing times vary by country (2 weeks to 6+ months). Criminal inadmissibility (IRPA s. 36): foreign nationals may be inadmissible for serious criminality (maximum sentence of 10+ years) or criminality (indictable offenses). Deemed rehabilitation automatic after 10 years for non-serious offenses. Individual rehabilitation applications can be submitted after 5-10 years depending on the offense. Temporary Resident Permits (TRPs) may be available for those who need to enter Canada despite inadmissibility.",
    citations: [
      { section: "IRPA s. 36 – Criminal Inadmissibility" },
      { section: "IRPR ss. 15-21 – Police Certificates" },
    ],
  },
  {
    id: "irpa-overview",
    title: "IRPA & IRPR — How Canadian Immigration Law Is Structured",
    category: "general",
    keywords: ["irpa", "irpr", "immigration and refugee protection act", "law", "regulations", "legislation", "statute"],
    content: "The Immigration and Refugee Protection Act (IRPA, 2001) is Canada's primary immigration statute; the Immigration and Refugee Protection Regulations (IRPR) contain the detailed rules that operationalize it. IRPA sets objectives (economic development, family reunification, protection of refugees, health and safety of Canadians) and defines core concepts: permanent resident, foreign national, temporary resident, and inadmissibility grounds (ss. 33-42). IRCC administers the system; the Canada Border Services Agency (CBSA) handles enforcement; the Immigration and Refugee Board (IRB) hears refugee claims and appeals. Annual levels plans set targets for economic, family, and humanitarian classes.",
    citations: [
      { section: "IRPA s. 3 – Objectives" },
      { section: "IRPA ss. 33-42 – Inadmissibility" },
    ],
  },
  {
    id: "inadmissibility-overview",
    title: "Inadmissibility Grounds (IRPA ss. 33-42)",
    category: "inadmissibility",
    keywords: ["inadmissible", "inadmissibility", "barred", "refused entry", "grounds", "deemed"],
    content: "Grounds of inadmissibility under IRPA: security (s.34), human or international rights violations (s.35), serious criminality (s.36(1) — sentence over 6 months or offence punishable by 10+ years) and criminality (s.36(2)), organized criminality (s.37), health conditions causing excessive demand (s.38 — threshold approximately $28,200 per year in 2025, updated annually), financial reasons — inability to support self/dependants (s.39), misrepresentation (s.40), non-compliance with the Act (s.41), and inadmissibility of an accompanying family member (s.42). Some grounds can be overcome via rehabilitation, TRP, H&C, or ministerial relief; security and human-rights grounds generally cannot.",
    citations: [
      { section: "IRPA ss. 33-42 – Inadmissibility Division" },
      { section: "IRPA s. 38(1)(c) – Excessive Demand" },
    ],
  },
  {
    id: "misrepresentation",
    title: "Misrepresentation (IRPA s. 40)",
    category: "inadmissibility",
    keywords: ["misrepresentation", "misrep", "false information", "fraud", "fake documents", "5 year ban", "omission"],
    content: "Misrepresentation (IRPA s.40) covers directly or indirectly withholding material facts, providing false information, or submitting fraudulent documents. Consequences: 5-year ban from applying for any status (including PR and citizenship), loss of pending applications, and potential finding against family members whose application relied on it. The ban applies even for innocent mistakes if facts were material — always correct errors proactively. Misrepresentation discovered after PR leads to revocation proceedings; after citizenship, to revocation. A procedural fairness letter normally precedes the finding so the applicant can respond.",
    citations: [
      { section: "IRPA s. 40 – Inadmissibility for Misrepresentation" },
      { section: "IRPR s. 40 – Application Disclosure" },
    ],
  },
  {
    id: "residency-obligation",
    title: "PR Residency Obligation (730 Days / 5 Years)",
    category: "pr-card",
    keywords: ["residency obligation", "730 days", "two years", "days outside canada", "pr card renewal", "abroad too long", "residing abroad"],
    content: "Permanent residents must be physically present in Canada at least 730 days in every rolling 5-year period (IRPA s.28). Days outside Canada still count if you: accompany a Canadian citizen or PR spouse/common-law partner (or parent, if a child), are employed full-time by a Canadian business or the public service abroad, or are the accompanying spouse of such an employee. If the obligation is not met, IRCC may issue a departure order; you can appeal to the Immigration Appeal Division (IAD) within 60 days on law/facts or H&C grounds. Officers may also consider H&C directly when assessing residency outside Canada.",
    citations: [
      { section: "IRPA s. 28 – Residency Obligation" },
      { section: "IRPA s. 63-64 – Residency Appeals (IAD)" },
    ],
  },
  {
    id: "pr-card-renewal",
    title: "PR Card — First Issuance & Renewal",
    category: "pr-card",
    keywords: ["pr card", "permanent resident card", "card renewal", "expired pr card", "wallet size", "maple leaf card"],
    content: "The Permanent Resident Card is the official proof of PR status for travel re-entry by commercial carrier. First card: issued after landing/conformation of PR (card fee $50). Renewal: apply if the card expires within 9 months, is lost/stolen/damaged, or name changed; fee $50; processing roughly 2-4 months. Renewal requires meeting the residency obligation for the 5 years before applying. If outside Canada with an expired card, apply for a Permanent Resident Travel Document (PRTD) at a visa office to return. Urgent processing/travel exceptions exist for documented emergencies.",
    citations: [
      { section: "IRPR ss. 268-278 – PR Cards and PRTDs" },
      { section: "IRCC Guide – Applying for a PR Card" },
    ],
  },
  {
    id: "citizenship-test",
    title: "Citizenship Test & Interview",
    category: "citizenship",
    keywords: ["citizenship test", "discover canada", "knowledge test", "pass mark", "interview", "fail test"],
    content: "Applicants aged 18-54 write the citizenship knowledge test based on the official 'Discover Canada' study guide. Format: 20 multiple-choice/true-false questions covering Canada's history, values, institutions, symbols, laws, and responsibilities of citizenship. Pass mark: 15/20 (75%), typically online with a 30-minute window, up to 3 attempts total. Failing all attempts triggers an interview with a citizenship officer who assesses knowledge orally. Language ability (CLB 4+) is assessed during the process for 18-54 applicants. Test invitations come after application eligibility review; oath ceremony follows approval.",
    citations: [
      { section: "Citizenship Regulation s. 14 – Knowledge Requirements" },
      { section: "IRCC – Discover Canada Study Guide" },
    ],
  },
  {
    id: "citizenship-presence-detail",
    title: "Citizenship Physical Presence Calculation",
    category: "citizenship",
    keywords: ["1095 days", "physical presence", "half days", "pre-pr credit", "calculator", "presence count", "tax years"],
    content: "Citizenship grant requires 1,095 days of physical presence within the 5 years immediately before applying (Citizenship Act s.5(1)(c)). Each day present as a temporary resident or protected person BEFORE becoming a PR counts as a half-day, credited up to a maximum of 365 days. Time serving a conditional sentence, on probation, or in removal order periods does not count. Applicants must have filed income taxes for at least 3 years within the 5-year window. Example: 365 pre-PR half-day credits + 730 days as PR = eligible minimum.",
    citations: [
      { section: "Citizenship Act s. 5(1)(c)-(e)" },
      { section: "Citizenship Regulation – Presence Credit Rules" },
    ],
  },
  {
    id: "refugee-protection-def",
    title: "Refugee Protection — Who Qualifies (IRPA ss. 95-97)",
    category: "refugee",
    keywords: ["refugee", "convention refugee", "person in need of protection", "persecution", "torture", "protection", "claim"],
    content: "Two protection categories under IRPA: Convention Refugee (s.96) — a person with a well-founded fear of persecution based on race, religion, nationality, political opinion, or membership in a particular social group, outside their country and unable/unwilling to avail themselves of its protection; and Person in Need of Protection (s.97) — someone in Canada facing torture, risk to life, or risk of cruel and unusual treatment/punishment, unable/unwilling of state protection, with risks not faced generally by others (no general risk like crime waves, poverty, or inadequate healthcare unless exceptional). Exclusions (s.98): war criminals, perpetrators of serious non-political crimes, and persons protected by another country do not qualify.",
    citations: [
      { section: "IRPA s. 96 – Convention Refugee" },
      { section: "IRPA s. 97 – Person in Need of Protection" },
      { section: "IRPA s. 98 – Exclusion Clauses" },
    ],
  },
  {
    id: "refugee-claims-process",
    title: "Refugee Claim Process & Timelines",
    category: "refugee",
    keywords: ["refugee claim", "rpd", "basis of claim", "boc", "hearing", "rad", "appeal refugee", "claim timeline"],
    content: "Refugee claims are made at a port of entry or inland at an IRCC office. Steps: (1) eligibility screening (security, criminality, prior claims, Safe Third Country Agreement at US land borders); (2) Basis of Claim (BOC) form due within 15 days of referral to the Refugee Protection Division (RPD); (3) RPD hearing before a decision-maker, usually 12-24 months after referral; (4) decision: acceptance grants protected-person status enabling PR application; rejection allows appeal to the Refugee Appeal Division (RAD) within 15 days, then judicial review at Federal Court (leave within 15 days). Failed claimants face a 1-year wait before PRRA eligibility. Interim federal health coverage and work permits are available to claimants.",
    citations: [
      { section: "IRPA ss. 99-111 – Refugee Protection Division" },
      { section: "IRPA s. 110 – RAD Appeals" },
      { section: "Safe Third Country Agreement" },
    ],
  },
  {
    id: "hc-s25",
    title: "Humanitarian & Compassionate Grounds (H&C)",
    category: "h-and-c",
    keywords: ["h and c", "humanitarian compassionate", "hc", "s25", "discretionary", "best interests of child", "establishment"],
    content: "H&C applications (IRPA s.25(1)) request PR exemption from normal requirements based on hardship. Key factors: establishment in Canada (employment, community ties, length of stay), best interests of children directly affected, hardships in home country (medical care unavailability, country conditions, violence, discrimination), and consequences of family separation. H&C cannot override certain inadmissibility grounds (security, human rights violations, serious criminality). A negative decision gets no appeal, only judicial review. Applications require significant evidence; processing is discretionary and lengthy. Inland spousal sponsorship already embeds an H&C-style assessment, so separate H&C is usually unnecessary there.",
    citations: [
      { section: "IRPA s. 25(1) – Humanitarian Consideration" },
      { section: "IRPA s. 25.1 – Public Policy Exemptions" },
    ],
  },
  {
    id: "prra",
    title: "Pre-Removal Risk Assessment (PRRA)",
    category: "refugee",
    keywords: ["prra", "pre removal risk", "risk assessment", "failed claimant", "removal", "one year bar"],
    content: "A PRRA is a paper-based risk assessment given to some people facing removal from Canada. Eligible groups: failed refugee claimants (only 12 months after final rejection, per IRPA s.112(3) bar), persons from an administration-of-justice moratorium country, and some refused PR applicants from countries with systemic risk issues. It applies the same protection tests as refugee claims (IRPA ss.96-97) using new evidence or evidence not reasonably available at the hearing. Positive PRRA = protected person status → PR application. No automatic stay of removal while most PRRAs are pending; decisions can be judicially reviewed.",
    citations: [
      { section: "IRPA s. 112 – PRRA Eligibility" },
      { section: "IRPA s. 113 – PRRA Assessment" },
    ],
  },
  {
    id: "removal-orders-types",
    title: "Removal Orders — Three Types",
    category: "enforcement",
    keywords: ["removal order", "departure order", "exclusion order", "deportation order", "removed canada", "cbc", "cbsa"],
    content: "Three removal orders under IRPA: Departure Order (s.229) — leave Canada within 30 days; becomes a deportation order automatically if ignored. Exclusion Order (s.230) — cannot return for 1 year generally, or 5 years where inadmissibility was based on misrepresentation; an Authorization to Return (ARC) is needed to come back before the period ends. Deportation Order (s.231) — permanent bar; ARC mandatory for any return. Removal orders come into force 30 days after decision unless appealed to the IAD (PRs/sponsored family) within 30 days or judicially reviewed. Stays of removal may be requested from CBSA on humanitarian grounds.",
    citations: [
      { section: "IRPA ss. 229-231 – Removal Orders" },
      { section: "IRPA s. 63 – Removal Order Appeals (IAD)" },
    ],
  },
  {
    id: "arc",
    title: "Authorization to Return to Canada (ARC)",
    category: "enforcement",
    keywords: ["arc", "authorization return", "return after deportation", "come back canada removed"],
    content: "An ARC is required to return to Canada after a deportation order, or an exclusion order where the exclusion period has not ended. The application assesses why you left/were removed, your current circumstances, rehabilitation, and whether return poses risk. There is a processing fee; approval is discretionary and often requires strong supporting evidence of changed circumstances. ARCs are submitted to the visa office responsible for your region alongside any new permit applications. Processing varies widely (months). If the underlying inadmissibility persists, other remedies (TRP, rehabilitation) may be needed simultaneously.",
    citations: [
      { section: "IRPA s. 52 – Requirement of ARC" },
      { section: "IRPR ss. 210-213 – Work Permits (contextual)" },
    ],
  },
  {
    id: "criminal-rehabilitation-detail",
    title: "Criminal Rehabilitation & Deemed Rehabilitation",
    category: "enforcement",
    keywords: ["rehabilitation", "deemed rehabilitated", "criminal record canada", "dui canada", "10 years", "individual rehabilitation"],
    content: "Criminality vs serious criminality (IRPA s.36): offences punishable by less than 10 years and sentences of 6 months or less = criminality; more serious = serious criminality (cannot be overcome by deemed rehabilitation). Deemed rehabilitation: automatic 10 years after completing sentence for non-serious single offences. Individual rehabilitation: apply after 5 years from sentence completion, showing stable life reform (fee $200, or $1,000 for serious criminality). DUI since 2018 counts as serious criminality (max 10-year sentence) requiring individual rehabilitation or TRP. Legal Opinion Letters from Canadian counsel help border officers assess equivalency.",
    citations: [
      { section: "IRPA s. 36 – Criminality Definitions" },
      { section: "IRPA s. 36(3)(a-b) – Equivalency" },
      { section: "IRPR ss. 18-19 – Rehabilitation Applications" },
    ],
  },
  {
    id: "trp",
    title: "Temporary Resident Permit (TRP)",
    category: "enforcement",
    keywords: ["trp", "temporary resident permit", "criminal entry canada", "overcome inadmissibility short term"],
    content: "A TRP (IRPA s.24) temporarily overrides inadmissibility (usually criminal or medical) when entry is justified by a compelling purpose and benefits outweigh risks. Validity scales with purpose: up to 3 years for criminal inadmissibility cases, shorter for one-off events. Standard fee $200 ($229.75 at some ports). TRPs can be issued at ports of entry (officer discretion) or at visa offices (recommended for planned travel). Holding a TRP for 5 consecutive years with clean conduct can lead to criminal rehabilitation recognition. TRP does NOT erase inadmissibility — it suspends it for the permit period only.",
    citations: [
      { section: "IRPA s. 24(1) – Temporary Resident Permits" },
      { section: "IRPR s. 299 – Fee Exemptions" },
    ],
  },
  {
    id: "noc-teer-system",
    title: "NOC 2021 & TEER Categories",
    category: "work-permit",
    keywords: ["noc", "teer", "national occupational classification", "occupation code", "teer 0", "skill level", "noc code"],
    content: "The National Occupational Classification (NOC 2021) replaced Skill Type 0/A/B/D categories with six TEER (Training, Education, Experience, Responsibilities) levels: TEER 0 — management jobs; TEER 1 — university-degree professions; TEER 2 — college diplomas or multi-year apprenticeships, supervisors; TEER 3 — apprenticeships/vocational training; TEER 4 — high-school-level occupations; TEER 5 — short demonstration-period work. Economic programs target TEER 0-3 (skilled work). Find your NOC via the Government of Canada NOC search using job duties — the lead statement and main duties must match your employment, which matters for Express Entry, LMIA applications, and PGWP field checks.",
    citations: [
      { section: "Statistics Canada – NOC 2021 Structure" },
      { section: "IRCC – TEER Category Guidance" },
    ],
  },
  {
    id: "ee-category-draws",
    title: "Express Entry Category-Based Draws",
    category: "express-entry",
    keywords: ["category draw", "category-based selection", "french draw", "healthcare draw", "stem draw", "trades draw", "targeted draw"],
    content: "Since mid-2023, IRCC runs targeted Express Entry draws by category chosen annually to match labour needs. Categories have included French-language proficiency (strongest CLB 7 French scores get priority), healthcare and social services, STEM occupations, trades (carpenters, electricians, plumbers), transport, agriculture/agri-food, and education (added 2025). Candidates qualify by having recent work experience (typically 6+ months continuous) in a listed occupation plus language thresholds — no separate application needed; qualifying profiles simply become eligible for category rounds. CRS cutoffs vary dramatically by round (French draws lowest; general draws highest). Check current-year criteria as lists change annually.",
    citations: [
      { section: "IRCC – Category-Based Selection Announcements" },
      { section: "IRPR s. 104 – Ministerial Instructions" },
    ],
  },
  {
    id: "fsw-points-grid",
    title: "FSW Six Selection Factors Point Grid",
    category: "express-entry",
    keywords: ["67 points", "point grid", "selection factors", "age points", "education points", "language points fsw"],
    content: "FSW needs 67/100 points across six factors. Age (max 12): 18-35 = 12 points, decreasing yearly after 35. Education (max 25): PhD 25, Master's 23, two+ credentials 22, Bachelor's 21, diploma varying lower, secondary 5. Language (max 28): first official language CLB 9+ = 6 points per ability (24 max), CLB 7-8 = 4-5 points; second language adds up to 4. Work experience (max 15): 6+ years = 15. Arranged employment (max 10) — valid LMIA-supported offer. Adaptability (max 10): spouse language CLB 4+, prior Canadian study/work, relative in Canada, etc. Meeting 67 makes you eligible for the pool — CRS then determines ITA chances.",
    citations: [
      { section: "IRPR s. 75-76 – Minimum Standards & Grid" },
      { section: "IRCC – FSW Points Calculator" },
    ],
  },
  {
    id: "iec-working-holiday",
    title: "International Experience Canada (IEC)",
    category: "work-permit",
    keywords: ["iec", "working holiday", "young professionals", "co-op internship", "youth mobility", "working holiday canada"],
    content: "IEC offers three streams for youth (generally ages 18-35; range varies 18-29/30/35 by partner country): Working Holiday — open work permit anywhere in Canada, requires ~CAD $2,500 in funds plus insurance; Young Professionals — employer-specific permit tied to a paid job matching career development, employer must commit employment; International Co-op Internship — student placement permit tied to curriculum requirement. Participation via country-specific pools each season; candidates enter draws after profile submission. Some countries limit lifetime participation or duration (12-24 months). Reciprocal agreements mean availability depends on your citizenship.",
    citations: [
      { section: "IRPR s. 205(d) – Youth Exchange" },
      { section: "IRCC – IEC Program Guidelines" },
    ],
  },
  {
    id: "global-talent-stream",
    title: "Global Talent Stream (GTS)",
    category: "work-permit",
    keywords: ["global talent stream", "gts", "fast track work permit", "tech worker canada", "2 week permit", "occupations in demand list"],
    content: "The Global Talent Stream fast-tracks high-skilled tech hiring. Two categories: Category A — employers referred by a designated partner organization hiring unique specialized talent; Category B — employers hiring from ESDC's Occupations In-Demand list (software engineers, data scientists, designers, digital media, etc., updated periodically). Service standard: LMIA within 10 business days, work permit target ~2 weeks. Employers commit to a Labour Market Benefits Plan with job creation/training milestones reported to ESDC; spouses get open work permits. Workers may also qualify for expedited port-of-entry processing under GTS exemptions.",
    citations: [
      { section: "ESDC – Global Talent Stream Employer Guide" },
      { section: "IRPR s. 203(2) – LMIA Variations" },
    ],
  },
  {
    id: "start-up-visa-program",
    title: "Start-Up Visa Program",
    category: "business-immigration",
    keywords: ["start-up visa", "suv", "entrepreneur", "letter of support", "designated organization", "venture capital angel incubator"],
    content: "The Start-Up Visa targets entrepreneurs building innovative businesses in Canada. Requirements: a Letter of Support from a designated organization — venture capital fund committing $200,000+, angel investor group committing $75,000+, or business incubator accepting the project (no investment floor) — plus CLB 5 language and settlement funds. Up to 5 co-founders may apply sharing one supported venture; each must hold 10%+ voting rights collectively controlling the company with a designated entity together. Commitment certificates cap applicants per designated org (2024 measure). Founders may obtain open work permits up to 3 years while PR processes. The business itself need not succeed — genuine intent suffices.",
    citations: [
      { section: "IRPR s. 98-100 – Start-Up Business Class" },
      { section: "IRCC – Designated Organizations List" },
    ],
  },
  {
    id: "self-employed-program",
    title: "Self-Employed Persons Program",
    category: "business-immigration",
    keywords: ["self employed program", "athlete immigration", "artist immigration", "cultural activities", "farm experience canada"],
    content: "The Self-Employed Persons Program serves those intending to be self-employed in cultural activities or athletics in Canada. Requirements: relevant experience — 2 years in the 5 years before applying either self-employed in cultural/athletic activities, participating at world-class level, or farm-management experience — plus intent and ability to be self-employed in Canada, scoring at least 35 points on a selection grid (experience, education, age, language, adaptability out of 100). Processing is notoriously long (several years). Demonstrating sustainable self-employment capacity through contracts, portfolio, business plan strengthens cases.",
    citations: [
      { section: "IRPR s. 100 – Self-Employed Class" },
      { section: "IRCC – Self-Employed Persons Guide" },
    ],
  },
  {
    id: "atlantic-immigration-program",
    title: "Atlantic Immigration Program (AIP)",
    category: "economic-programs",
    keywords: ["atlantic immigration", "aip", "atlantic canada", "newfoundland", "pei", "nova scotia", "new brunswick", "maritimes"],
    content: "The Atlantic Immigration Program (permanent since 2022) lets employers in Newfoundland and Labrador, PEI, Nova Scotia, and New Brunswick hire foreign workers without LMIA. Requirements: job offer from a designated Atlantic employer (non-seasonal, TEER 0-4, at least 1 year), settlement plan approved by the province, endorsement certificate from the provincial government, education (ECA if foreign), and language CLB 5 (TEER 0-3) or CLB 4 (TEER 4). Prior work experience requirements scale with TEER; international graduates of Atlantic institutions are exempt. PR processing ~12 months; employers must also connect newcomers with settlement services.",
    citations: [
      { section: "IRPR s. 10.1 – Atlantic Immigration Class" },
      { section: "IRCC – AIP Employer Designation" },
    ],
  },
  {
    id: "quebec-immigration-system",
    title: "Quebec Immigration (CSQ, PEQ, Arrima)",
    category: "economic-programs",
    keywords: ["quebec", "csq", "certificat de selection", "peq", "arrima", "quebec skilled worker", "montreal immigration", "french requirement quebec"],
    content: "Quebec selects its own economic immigrants under the Canada-Québec Accord; the federal government then screens admissibility only. Selected applicants receive a Certificat de sélection du Québec (CSQ) via the Arrima expression-of-interest portal (Regular Worker Program scoring French, work experience, age, education). The Programme de l'expérience québécoise (PEQ) offers CSQs to Quebec graduates (diploma + advanced intermediate French oral level 7) and temporary workers with Quebec experience. French proficiency became mandatory for most economic streams following 2024 reforms. Spouses also must demonstrate basic spoken French for PEQ. After CSQ, apply federally for PR (medical/security).",
    citations: [
      { section: "Canada-Québec Accord (1991)" },
      { section: "MIFI – Programme régulier des travailleurs qualifiés" },
    ],
  },
  {
    id: "dependent-children-lock-in-age",
    title: "Dependent Children & Lock-In Age",
    category: "family-sponsorship",
    keywords: ["dependent child", "lock in age", "under 22", "child sponsorship", "dependant definition", "overage dependant"],
    content: "A dependent child is under 22 and without a spouse/partner (IRPR s.1(3)); the age locks in when IRCC receives the complete sponsorship application (e-Ticket date). Children 22+ qualify only if both conditions met: they depended substantially on parental financial support AND a mental or physical condition has made them unable to support themselves since before age 22 — medical documentation essential. All dependent children must be declared and examined even if not accompanying (non-accompanying declaration); failure means future sponsorship bans. Custody/access letters and consent-to-travel documents matter for separated parents.",
    citations: [
      { section: "IRPR s. 1(3) – Dependent Child Definition" },
      { section: "RRO 2017-157 – Lock-In Age Amendment" },
    ],
  },
  {
    id: "bridging-open-work-permit",
    title: "Bridging Open Work Permit (BOWP)",
    category: "work-permit",
    keywords: ["bridging open work permit", "bowp", "open permit while pr processing", "work permit expiring pr"],
    content: "A BOWP lets principal applicants (and eligible spouses) keep working while their PR application processes. Eligibility: PR application submitted under Express Entry (CEC/FSTP/FSWP), certain PNP streams, Home Child Care/Home Support pilots, or Agri-Food pilot; current work permit valid but expiring within 4 months; physical presence in Canada when applying. Issues as a 1-year open permit, renewable until a final PR decision. Apply online before current permit expires to maintain status; fees mirror standard work permit ($155 + open permit holder $100). Not available to outland applicants or those with expired status needing restoration.",
    citations: [
      { section: "IRPR s. 205(c)(ii) – Significant Benefit" },
      { section: "IRCC – BOWP Eligibility Guide" },
    ],
  },
  {
    id: "visitor-record-extension",
    title: "Extending Your Stay — Visitor Records",
    category: "visitor",
    keywords: ["extend visitor visa", "visitor record", "extension canada", "stay longer", "apply extension", "before expiry"],
    content: "To stay longer than authorized, apply for a Visitor Record before your status expires (ideally 30+ days ahead). Maintained status keeps you lawful under the same conditions while IRCC decides — leaving Canada voids maintained status. Visitor records cannot authorize work or study by themselves. Requirements: passport validity beyond requested extension, funds for the extended stay, ties to home country, and explanation for the longer visit (tourism itinerary, family visit details). Typical extensions add 3-6 months. Refusals carry no appeal; re-entry on original TRV remains possible if still valid.",
    citations: [
      { section: "IRPR s. 183 – Extension Applications" },
      { section: "IRPR s. 186(1)(b) – Maintained Status" },
    ],
  },
  {
    id: "eta-electronic-travel",
    title: "Electronic Travel Authorization (eTA)",
    category: "visitor",
    keywords: ["eta", "electronic travel authorization", "visa exempt flying", "eta validity", "air travel canada"],
    content: "Visa-exempt foreign nationals flying to (or transiting through) Canada need an eTA — a $7 electronic screening linked to your passport, applied online in minutes with most approvals instant. Validity: 5 years or until passport expires, whichever comes first; multiple entries permitted. Exceptions: US citizens need nothing; visa-required nationals need TRVs instead; land/sea arrivals (driving, cruise) don't need eTAs. Recent eTA expansion lets eligible visa-required travellers who held a Canadian visa in the past 10 years (or hold a US non-immigrant visa) fly with eTA instead of TRV. Always update eTA after passport renewal.",
    citations: [
      { section: "IRPR s. 12.01-12.05 – eTA Requirements" },
      { section: "IRCC – eTA Expansion Policy 2023" },
    ],
  },
  {
    id: "study-permit-financial-pal",
    title: "Study Permit Financial Proof & PAL Requirements",
    category: "study-permit",
    keywords: ["provincial attestation letter", "pal", "tal", "gic amount student", "proof funds student", "22895", "20635", "study permit funds"],
    content: "Study permit applicants outside Quebec must show tuition + living funds of CAD $22,895 (effective Sept 1, 2025; raised from $20,635 set January 2024) + transportation, ideally via GIC, bank statements, or education loans. Since January 22, 2024, most applicants also need a Provincial Attestation Letter (PAL/TAL) issued by the province of study — annual intake caps drive this requirement. Exemptions: master's and doctoral students, elementary/secondary students, and exchange students. DLIs report enrollment compliance; PAL-less applications are returned. Quebec uses its own CAQ system instead of PALs. Plan 3-6 months ahead given caps and processing variability.",
    citations: [
      { section: "IRPR s. 220 – Financial Requirements" },
      { section: "IRCC – PAL/TAL Cap Framework 2024" },
    ],
  },
  {
    id: "pgwp-field-language-updates",
    title: "PGWP Field-of-Study & Language Updates",
    category: "study-permit",
    keywords: ["pgwp field of study", "pgwp language requirement", "clb 7 pgwp", "college graduate pgwp", "eligible fields pgwp"],
    content: "Post-graduation rules tightened November 2024. Language: graduates must show CLB 7 (university bachelor/master/doctoral degree holders) or CLB 5 (college/other program graduates) in English or French — test results valid 2 years, submitted with PGWP application. Field of study: college/non-degree graduates must enroll in programs aligned with long-term labour-shortage fields (healthcare, STEM, trades, transport, agriculture — list refreshed periodically); university degree graduates are exempt regardless of field. PGWP length remains program-length based (min 8-month program; 3-year maximum for 2+-year programs). Verify your DLI program's PGWP eligibility BEFORE enrolling.",
    citations: [
      { section: "IRPR s. 205(c)(ii) – Significant Benefit" },
      { section: "IRCC – PGWP Eligibility Criteria Update Nov 2024" },
    ],
  },
  {
    id: "off-campus-work-hours",
    title: "Off-Campus Work Hour Limits",
    category: "study-permit",
    keywords: ["off campus hours", "24 hours", "work while studying", "how many hours student", "part time student work"],
    content: "International students may work off-campus up to 24 hours per week during academic sessions — permanently raised from 20 hours in November 2024 (the pandemic-era full-time exemption ended). Full-time unlimited work remains allowed during scheduled breaks (reading weeks, summer, winter holidays) for students actively enrolled full-time. Conditions: valid study permit listing off-campus authorization, enrolled at a DLI in a 6+-month program leading to a degree/diploma/certificate, ongoing compliance with enrollment. Working beyond authorized hours violates permit conditions and risks status. On-campus work stays unrestricted for full-time students.",
    citations: [
      { section: "IRPR s. 186(v) – Off-Campus Employment" },
      { section: "IRCC – Off-Campus Hours Announcement 2024" },
    ],
  },
];

export default entries;
